# Generated by Django 6.0.2 on 2026-02-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('nuevo', 'Disponible (Nuevo) ✨'), ('instalado', 'Instalado en Cliente 🏠'), ('falla', 'Retirado por Falla ⚠️'), ('bodega', 'En Bodega (Para Revisión) 📦'), ('cambiado', 'Equipo Sustituido/Cambiado 🔄')], default='nuevo', max_length=20)),
                ('serie_retirada', models.CharField(blank=True, help_text='Si es un cambio, ¿qué serie falló?', max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
